# Generated by Django 5.1.6 on 2025-02-24 14:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Profile Photo')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('interested_course', models.CharField(choices=[('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Cyber Security', 'Cyber Security'), ('Digital Marketing', 'Digital Marketing'), ('Software Engineering', 'Software Engineering'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learning', 'Machine Learning'), ('Cloud Computing', 'Cloud Computing'), ('Blockchain', 'Blockchain')], max_length=50, verbose_name='Interested Course')),
                ('remarks', models.TextField(verbose_name='Remarks')),
                ('date_of_register', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date of Registration')),
            ],
        ),
    ]
